### PR TITLE
Add schedule MVP

### PR DESCRIPTION
**Pull request by evantarrh**
Some of this is hardcoded, simply because we don't have enough information about the events/everything else.

Also, can someone pls double check/confirm/correct me on the starting date (Sat Jan 30) and the start of the workshops/etc (Sun Jan 31?)

screenshot 2016-01-21 09 44 33

### CODE REVIEW

**Comment by eunicekokor** [comment]
there are no events on Sunday I think

**Comment by mattpiccolella** [comment]
Are the nightly workspaces included? They're not on the screenshot (can't look at code on phone)

**Comment by eunicekokor** [comment]
yes they are @mjp2220 they're called "Workspaces"

**Comment by eunicekokor** [comment]
looks good to me, I just need a confirmation that the workspaces start Monday in order to merge

**Comment by mattpiccolella** [comment]
Yes they start Monday, I think we can ship

**Comment by evantarrh** [comment]
If they start Monday, we need to change the code lol. I'll push and then we'll be all set :+1:

**Comment by evantarrh** [comment]
OK, this should be good to go!

**Pull request merged**
